title: daegkim.github.io
email: daegeunkim92@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""
github_username: daegkim

# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  flutter:
    output: true

defaults:
  - scope:
      path: ""
      type: "flutters"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"